name = "idea-box"
main = "src/worker.js"
compatibility_date = "2024-11-05"
compatibility_flags = ["nodejs_compat"]

# Workers.dev subdomain
workers_dev = true

[site]
bucket = "./dist"

[[r2_buckets]]
binding = "IDEA_BOX_STORAGE"
bucket_name = "idea-box"

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true
