name = "idea-box"
main = "src/worker.js"
compatibility_date = "2025-11-06"
compatibility_flags = ["nodejs_compat"]

# Workers.dev subdomain
workers_dev = true

[site]
bucket = "./dist"

[[r2_buckets]]
binding = "IDEA_BOX_STORAGE"
bucket_name = "idea-box"
